#!/bin/bash
#
# command for switching between repos
set -ue

StashFile="$HOME/.repo_list.txt"

usage() {
		echo '-f force rebuild';
}

while test $# != 0
do
	case "$1" in
		-f) force_update=t ;;
		--) shift; break;;
		*)  usage; exit ;;
	esac
	shift
done

if [ ! -f "$StashFile" ] || [ ! -z ${var+force_update} ]; then
	echo "recreating cache"
	find ~/src -name '.cache' -prune -o -name '.git' -type d -prune -print0 | xargs -0 -n1 dirname | sed "s#$HOME#~#" > "$StashFile"
fi
FILE=$(fzf <"$StashFile" | sed "s#~#$HOME#");
cd "$FILE";
